### ISSUE TITLE
CC send

### ISSUE THREAD

**Issue by umekzg** [FanatiQS/wireless_atem_camera_control_and_tally#10]
Hi!

Is there any sample code to send over udp Camera Control values?

Thx!

**Comment by FanatiQS** [comment]
Do you mean for the API in `/src/atem.h`, microcontroller firmware or ATEM proxy?

There are no samples for sending any data. It is absolutely possible to do, but you would need to store the transmitted data for acknowledgements and handle that manually.

This project is mainly build for listening to camera control data from ATEM and not focused on sending data.

Let me know more what you are looking for and I'll try go help as best I can.

/Gustav

**Comment by umekzg** [comment]
I wanted to build a CC panel for my BMD cameras, something simple so i can drive iris and white balance without Atem software control.

ESP8266 works but just how you described, one way. 
With debug on serial i read "Got camera control data..." when i change something...
I just can't figure it out how to send CC data to ATEM and/or read it in meaningful way.

Any help is much appreciated. I'm willing to pay for your time...

Thx!

**Comment by FanatiQS** [comment]
Okay, I see. Do you want to build it as a mac/linux/windows application or microcontroller hardware control panel?
I assume you still want them connected to an ATEM switcher, just not use software control, right?

How do you want to read the camera control data? The firmware is built to write it to an SDI shield over I2C, but the API can be used to get the raw CC data for custom implementations.

Feel free to describe how you intent to use it it you want. That way it might be easier for me to understand what components you need.

/Gustav

**Comment by umekzg** [comment]
> Okay, I see. Do you want to build it as a mac/linux/windows application or microcontroller hardware control panel? 
Just the microcontroller.

>I assume you still want them connected to an ATEM switcher, just not use software control, right?
Yes.
 
> How do you want to read the camera control data? The firmware is built to write it to an SDI shield over I2C, but the API can be used to get the raw CC data for custom implementations.
API (UDP)

> Feel free to describe how you intent to use it it you want. That way it might be easier for me to understand what components you need.

I want to have option to send CC data to ATEM via UDP on esp8266.

**Comment by FanatiQS** [comment]
Okay, got it. Do you intent to send the CC data from the Arduino loop function on a separate device from the on communicating with the camera or do you want to do everything on the same device?

**Comment by umekzg** [comment]
Everything on the same device.
Plan is to go simple and test how stable the API is.

**Comment by FanatiQS** [comment]
Okay. What is your plan for input/output of the camera control data?
I personally think the simplest data pipeline is SoftwareControl -> ATEM -> ESP8266 -> SDI shield -> Camera. That way, the ESP is only relaying CC data from ATEM to Camera. How do you intend to input and output data? If you send CC data from device to ATEM, you still probably want to wait for that same data from ATEM back to ESP to not get out-of-order issues. What is your pipeline plan?

**Comment by umekzg** [comment]
ESP or Software Control (IP UDP) -> ATEM (SDI) -> CAM

**Comment by FanatiQS** [comment]
Ahh, you don't intent to output camera control data to the camera from the ESP8266 then?

**Comment by umekzg** [comment]
Can we continue the chat on whatsapp?
I can send you my contact info via email.

**Comment by FanatiQS** [comment]
Unfortunately, I don't have whatsapp. What about Discord or something?
